title: 2shine Docs
author:
  name: 'Github User'
  email: 'github@example.com'
description: >- # this means to ignore newlines until "baseurl:"
  An awesome documentation for the awesome 2shine. 

excerpts:
  # Displays or hides post excerpts from home layout post listing.
  show: true
  # Cuts off excerpts with an ellipsis (...) after 32 words (approx. 2 lines).
  # You can also leave this false, and manually control excerpt length:
  # https://jekyllrb.com/docs/posts/#post-excerpts
  auto_truncate: true

# Theme configuration
bootstrap:
  # Theme date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # If you want to link only specific pages in your header, uncomment
  # this and add the path to the page *files* in order as they should show up
  #header_pages:
  # - about.md

  # generate social links in footer
  social_links:
    twitter: 'https://twitter.com/jonaharagon'
    github:  'https://github.com/jonaharagon'
    #facebook: 'https://example.com/@jekyllrb'
    #instagram: 'https://example.com/@jekyllrb'
    #linkedin: 'https://example.com/@jekyllrb'
    #google: 'https://example.com/@jekyllrb'
    #youtube: 'https://example.com/@jekyllrb'
    #twitch: 'https://example.com/@jekyllrb'
    #telegram: 'https://example.com/@jekyllrb'
    #whatsapp: 'https://example.com/@jekyllrb'
    #discord: 'https://example.com/@jekyllrb'
    #slack: 'https://example.com/@jekyllrb'


# Build settings
theme: jekyll-bootstrap-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

destination:  docs